#!/bin/bash
# ==============================================================================
# Indhan LPG Monitoring System - Database & API Seeding Script
# Team Bourbon | Hack X '26
# ==============================================================================
#
# This script handles the ingestion of synthetic cylinder weight readings
# and static metadata generated by Member A into the backend system (Member C).
#
# Usage:
#   chmod +x scripts/seed_demo_data.sh
#   ./scripts/seed_demo_data.sh [api|db]
#
# ==============================================================================

# Exit on error
set -e

# Configuration
API_URL="http://localhost:8000/api"
READINGS_CSV="ml-engine/data_generator/output/seed_readings.csv"
READINGS_JSON="ml-engine/data_generator/output/seed_readings.json"
METADATA_JSON="ml-engine/data_generator/output/cylinder_metadata.json"
BACKEND_SEED_DIR="backend/seed"

MODE=${1:-"db"}

echo "=== Running Indhan Demo Seeding [Mode: $MODE] ==="

if [ "$MODE" = "db" ]; then
    echo "Using direct database seeding..."
    echo "Copying seed datasets to backend repository..."
    
    # Create backend seed dir if not exists
    mkdir -p "$BACKEND_SEED_DIR"
    
    # Copy files
    cp "$METADATA_JSON" "$BACKEND_SEED_DIR/cylinder_metadata.json"
    cp "$READINGS_CSV" "$BACKEND_SEED_DIR/seed_readings.csv"
    cp "$READINGS_JSON" "$BACKEND_SEED_DIR/seed_readings.json"
    
    echo "Files successfully copied to $BACKEND_SEED_DIR/"
    echo "Member C can now import these directly into SQLite/PostgreSQL."
    
elif [ "$MODE" = "api" ]; then
    echo "Using API ingestion endpoint seeding..."
    
    # 1. Register Cylinders first
    echo "Registering cylinders via API..."
    num_cylinders=$(jq '. | length' "$METADATA_JSON" 2>/dev/null || grep -c '"cylinder_id"' "$METADATA_JSON" || echo "5")
    echo "Found $num_cylinders cylinders."
    
    # Simulating API requests using curl for metadata
    # We loop through cylinder metadata records and post to /cylinders
    jq -c '.[]' "$METADATA_JSON" | while read -r cylinder; do
        cylinder_id=$(echo "$cylinder" | jq -r '.cylinder_id')
        echo "Posting metadata for $cylinder_id..."
        curl -s -X POST "$API_URL/cylinders" \
             -H "Content-Type: application/json" \
             -d "$cylinder" > /dev/null
    done
    
    # 2. Upload Telemetry (Bulk Ingestion)
    echo "Uploading bulk readings (7200 telemetry points) to API..."
    curl -s -X POST "$API_URL/readings/bulk" \
         -H "Content-Type: application/json" \
         -d @"$READINGS_JSON" > /dev/null
         
    echo "API seeding completed successfully."
else
    echo "Error: Unknown mode. Use 'db' or 'api'."
    exit 1
fi

echo "=== Seeding Completed ==="
